version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops

  nginx:
    build: ./nginx-site
    container_name: nginx-site
    ports:
      - "80:80"
    networks:
      - devops

volumes:
  jenkins_home:
    external: true

networks:
  devops:
    driver: bridge
