pipeline {
    agent any 

    environment {
        IMAGE_NAME = 'nginx-static'
        TAG = 'latest'
        DOCKER_HUB_USERNAME = 'saranshdocker12'
    }

    stages {

        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/saransh-del/Jenkins-Pipeline-Project.git',
                    branch: 'main',
                    credentialsId: 'git-auth-jenkins-credential-saranshdel'
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${TAG} nginx-site"
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        echo "Logged in to DockerHub"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        sh "docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${TAG}"
                    }
                }
            }
        }
    }
}
