pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')  // DockerHub credentials ID in Jenkins
        GITHUB_TOKEN = credentials('git-auth-jenkins-credential-saranshdel')  // GitHub token ID in Jenkins
        DOCKERHUB_REPO = 'saranshdocker12/nginx-static'  // Your DockerHub image name
        TAG = 'latest'
    }

    triggers {
        pollSCM('* * * * *')  // Poll GitHub every minute
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/saransh-del/Jenkins-Pipeline-Project.git',
                    branch: 'main',
                    credentialsId: 'git-auth-jenkins-credential-saranshdel'
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build --no-cache -t ${DOCKERHUB_REPO}:${TAG} -f nginx-site/Dockerfile nginx-site"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    sh "echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin"
                    sh "docker push ${DOCKERHUB_REPO}:${TAG}"
                }
            }
        }

        stage('Restart NGINX Container') {
            steps {
                script {
                    sh '''
                        docker stop nginx || true
                        docker rm nginx || true
                        docker run -d --name nginx -p 80:80 saranshdocker12/nginx-static:latest
                    '''
                }
            }
        }
    }
}
